//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IODemo {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Breakout module using socket 14 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Breakout breakout14;
        
        /// <summary>The Breakout module using socket 7 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Breakout breakout7;
        
        /// <summary>The MaxO module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MaxO maxO;
        
        /// <summary>The USB Client DP module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBClientDP usbClientDP;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZHydra Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZHydra)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZHydra();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.breakout14 = new GTM.GHIElectronics.Breakout(14);
            this.breakout7 = new GTM.GHIElectronics.Breakout(7);
            this.maxO = new GTM.GHIElectronics.MaxO(3);
            this.usbClientDP = new GTM.GHIElectronics.USBClientDP(2);
        }
    }
}
